# Generated by Django 6.0.3 on 2026-03-24 20:16

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Physician',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('specialization', models.CharField(choices=[('pediatrician', 'Pediatrician'), ('neonatologist', 'Neonatologist'), ('gp', 'General Practitioner'), ('lactation', 'Lactation Consultant'), ('nutritionist', 'Pediatric Nutritionist')], max_length=30)),
                ('hospital', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='physicians/')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(default='Kenya', max_length=100)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('suspended', 'Suspended')], default='pending', max_length=15)),
                ('is_available', models.BooleanField(default=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('registered_by_doctor', models.BooleanField(default=False)),
                ('registration_email', models.EmailField(blank=True, max_length=254)),
                ('registration_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Physician',
                'verbose_name_plural': 'Physicians',
                'ordering': ['-rating', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='PhysicianRegistrationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('specialization', models.CharField(choices=[('pediatrician', 'Pediatrician'), ('neonatologist', 'Neonatologist'), ('gp', 'General Practitioner'), ('lactation', 'Lactation Consultant'), ('nutritionist', 'Pediatric Nutritionist')], max_length=30)),
                ('hospital', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('license_number', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Any additional info')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhysicianReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('is_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physician_reviews', to=settings.AUTH_USER_MODEL)),
                ('physician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='physicians.physician')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('physician', 'mother')},
            },
        ),
    ]
